// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhNskpJRhvz_Di10p5Q4wR0I9P1Wes_uw',
    appId: '1:895972248156:web:fd79d82c69fff013dcf499',
    messagingSenderId: '895972248156',
    projectId: 'map-69450',
    authDomain: 'map-69450.firebaseapp.com',
    storageBucket: 'map-69450.appspot.com',
    measurementId: 'G-VZP437DXSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG-D6wt4GtPLWdcozArc4tWNUO-Tp9_uA',
    appId: '1:895972248156:android:eaa19c4b7e69a290dcf499',
    messagingSenderId: '895972248156',
    projectId: 'map-69450',
    storageBucket: 'map-69450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWEUUnTbXs5a7eK67MirkudY62lLAIeL0',
    appId: '1:895972248156:ios:1acbbe0f137b68f8dcf499',
    messagingSenderId: '895972248156',
    projectId: 'map-69450',
    storageBucket: 'map-69450.appspot.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWEUUnTbXs5a7eK67MirkudY62lLAIeL0',
    appId: '1:895972248156:ios:1acbbe0f137b68f8dcf499',
    messagingSenderId: '895972248156',
    projectId: 'map-69450',
    storageBucket: 'map-69450.appspot.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhNskpJRhvz_Di10p5Q4wR0I9P1Wes_uw',
    appId: '1:895972248156:web:109568018de8db46dcf499',
    messagingSenderId: '895972248156',
    projectId: 'map-69450',
    authDomain: 'map-69450.firebaseapp.com',
    storageBucket: 'map-69450.appspot.com',
    measurementId: 'G-14TR7KVD3M',
  );
}
